--- #YAML:1.0
name:               MySQL-Sandbox
version:            3.0.43
abstract:           Quickly installs MySQL side server, either standalone or in groups
author:
    - Giuseppe Maxia <gmax@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:  1
    Socket:      1.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
